# First, serve the static HTML files for page navigation
[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

# Handle streaming endpoint with longer timeouts
[[redirects]]
  from = "/api/chat/stream"
  to = "https://www.liftingchat.com/chat/stream"
  status = 200
  force = true
  methods = ["POST"]
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type", Cache-Control = "no-cache" }

# Regular API endpoints
[[redirects]]
  from = "/api/chat"
  to = "https://www.liftingchat.com/chat"
  status = 200
  force = true
  methods = ["POST"]
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type", Cache-Control = "no-cache" }

[[redirects]]
  from = "/api/auth/*"
  to = "https://www.liftingchat.com/auth/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type", Cache-Control = "no-cache" }

# Handle OPTIONS preflight requests
[[redirects]]
  from = "/api/*"
  to = "https://www.liftingchat.com/:splat"
  status = 200
  methods = ["OPTIONS"]
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, OPTIONS", Access-Control-Allow-Headers = "Content-Type", Access-Control-Max-Age = "86400" }