[[redirects]]
  from = "/api/*"
  to = "https://liftingchat.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
  methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]