# First, serve the static HTML files for page navigation
[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

# Then handle API requests
[[redirects]]
  from = "/api/chat"
  to = "https://www.liftingchat.com/chat"
  status = 200
  force = true
  methods = ["POST"]
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/chat/stream"
  to = "https://www.liftingchat.com/chat/stream"
  status = 200
  force = true
  methods = ["POST"]
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/auth/*"
  to = "https://www.liftingchat.com/auth/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*"}