# Redirect API requests to your backend
[[redirects]]
  from = "/api/*"
  to = "https://www.liftingchat.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization"}

# Fallback redirect for SPA navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200