# Redirect all API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://www.liftingchat.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"}

# Handle CORS preflight requests
[[redirects]]
  from = "/api/*"
  to = "https://www.liftingchat.com/:splat"
  status = 200
  force = true
  methods = ["OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"}

# Redirect all non-specific paths to index.html (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200